apiVersion: 1

datasources:
  - name: Trino Iceberg
    uid: trino-iceberg
    type: trino-datasource
    access: proxy
    url: http://noc-trino:8080
    isDefault: false
    editable: true

    jsonData:
      catalog: iceberg
      schema: noc
      username: admin
