# Extra logging configuration
status = ERROR
name = SparkLog4j2

# Appender configuration
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}: %m%n

# Root logger level
rootLogger.level = WARN
rootLogger.appenderRef.stdout.ref = STDOUT

# Application loggers
logger.spark.name = org.apache.spark
logger.spark.level = WARN

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = WARN

logger.noc.name = noc.spark
logger.noc.level = INFO
