connector.name=iceberg
iceberg.catalog.type=TESTING_FILE_SYSTEM
iceberg.file-system-catalog.warehouse=s3://noc-raw-data/iceberg-warehouse
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.aws-access-key=minioadmin
s3.aws-secret-key=minioadmin
s3.path-style-access=true
